# Generated by Django 3.2.9 on 2021-12-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211213_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='genero',
            new_name='gender',
        ),
    ]
