# Generated by Django 3.2.9 on 2021-12-14 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='codregistro',
            new_name='registration_code',
        ),
    ]
