# Generated by Django 3.2.9 on 2021-12-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_codregistro_user_registration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
