# Generated by Django 3.2.9 on 2021-12-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_registration_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_employees',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
