# Generated by Django 3.2.9 on 2021-12-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_avatar_employees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar_employees',
            new_name='avatar_users',
        ),
    ]
