# Generated by Django 3.2.9 on 2021-11-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chief',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
