# Generated by Django 4.0 on 2021-12-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
