# Generated by Django 4.0 on 2021-12-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_full_name_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='full_name_id',
            new_name='full_name',
        ),
    ]
