# Generated by Django 3.2.9 on 2021-11-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='numero',
        ),
    ]
