# Generated by Django 4.0 on 2021-12-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_full_name_id_employee_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
    ]
