# Generated by Django 3.2.9 on 2021-11-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
