# Generated by Django 3.2.9 on 2021-11-29 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='anulate',
        ),
    ]
